<?php

/**
 * BaseResourceLine
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $resource_id
 * @property clob $source_text
 * @property clob $remarks
 * @property Resource $Resource
 * @property Doctrine_Collection $Translations
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method integer             getResourceId()   Returns the current record's "resource_id" value
 * @method clob                getSourceText()   Returns the current record's "source_text" value
 * @method clob                getRemarks()      Returns the current record's "remarks" value
 * @method Resource            getResource()     Returns the current record's "Resource" value
 * @method Doctrine_Collection getTranslations() Returns the current record's "Translations" collection
 * @method ResourceLine        setId()           Sets the current record's "id" value
 * @method ResourceLine        setResourceId()   Sets the current record's "resource_id" value
 * @method ResourceLine        setSourceText()   Sets the current record's "source_text" value
 * @method ResourceLine        setRemarks()      Sets the current record's "remarks" value
 * @method ResourceLine        setResource()     Sets the current record's "Resource" value
 * @method ResourceLine        setTranslations() Sets the current record's "Translations" collection
 * 
 * @package    xliffeditor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseResourceLine extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('resource_line');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('resource_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('source_text', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('remarks', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Resource', array(
             'local' => 'resource_id',
             'foreign' => 'id'));

        $this->hasMany('ResourceLineTranslation as Translations', array(
             'local' => 'id',
             'foreign' => 'line_id'));
    }
}