<?php

/**
 * BaseProjectLanguage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $project_id
 * @property string $name
 * @property string $lang
 * @property Project $Project
 * @property Doctrine_Collection $Resource
 * @property Doctrine_Collection $ResourceLineTranslation
 * 
 * @method integer             getId()                      Returns the current record's "id" value
 * @method integer             getProjectId()               Returns the current record's "project_id" value
 * @method string              getName()                    Returns the current record's "name" value
 * @method string              getLang()                    Returns the current record's "lang" value
 * @method Project             getProject()                 Returns the current record's "Project" value
 * @method Doctrine_Collection getResource()                Returns the current record's "Resource" collection
 * @method Doctrine_Collection getResourceLineTranslation() Returns the current record's "ResourceLineTranslation" collection
 * @method ProjectLanguage     setId()                      Sets the current record's "id" value
 * @method ProjectLanguage     setProjectId()               Sets the current record's "project_id" value
 * @method ProjectLanguage     setName()                    Sets the current record's "name" value
 * @method ProjectLanguage     setLang()                    Sets the current record's "lang" value
 * @method ProjectLanguage     setProject()                 Sets the current record's "Project" value
 * @method ProjectLanguage     setResource()                Sets the current record's "Resource" collection
 * @method ProjectLanguage     setResourceLineTranslation() Sets the current record's "ResourceLineTranslation" collection
 * 
 * @package    xliffeditor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProjectLanguage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project_language');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('project_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('lang', 'string', 5, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Project', array(
             'local' => 'project_id',
             'foreign' => 'id'));

        $this->hasMany('Resource', array(
             'local' => 'id',
             'foreign' => 'base_language_id'));

        $this->hasMany('ResourceLineTranslation', array(
             'local' => 'id',
             'foreign' => 'language_id'));
    }
}