<?php

/**
 * BaseTranslationProjectLanguage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $project_id
 * @property string $name
 * @property string $lang
 * @property TranslationProject $Project
 * 
 * @method integer                    getId()         Returns the current record's "id" value
 * @method integer                    getProjectId()  Returns the current record's "project_id" value
 * @method string                     getName()       Returns the current record's "name" value
 * @method string                     getLang()       Returns the current record's "lang" value
 * @method TranslationProject         getProject()    Returns the current record's "Project" value
 * @method TranslationProjectLanguage setId()         Sets the current record's "id" value
 * @method TranslationProjectLanguage setProjectId()  Sets the current record's "project_id" value
 * @method TranslationProjectLanguage setName()       Sets the current record's "name" value
 * @method TranslationProjectLanguage setLang()       Sets the current record's "lang" value
 * @method TranslationProjectLanguage setProject()    Sets the current record's "Project" value
 * 
 * @package    xliffeditor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTranslationProjectLanguage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('translation_project_language');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('project_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('lang', 'string', 5, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TranslationProject as Project', array(
             'local' => 'project_id',
             'foreign' => 'id'));
    }
}