<?php

/**
 * BaseResourceLineTranslation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $line_id
 * @property integer $language_id
 * @property clob $target_text
 * @property clob $remarks
 * @property ResourceLine $Line
 * @property ProjectLanguage $Language
 * 
 * @method integer                 getLineId()      Returns the current record's "line_id" value
 * @method integer                 getLanguageId()  Returns the current record's "language_id" value
 * @method clob                    getTargetText()  Returns the current record's "target_text" value
 * @method clob                    getRemarks()     Returns the current record's "remarks" value
 * @method ResourceLine            getLine()        Returns the current record's "Line" value
 * @method ProjectLanguage         getLanguage()    Returns the current record's "Language" value
 * @method ResourceLineTranslation setLineId()      Sets the current record's "line_id" value
 * @method ResourceLineTranslation setLanguageId()  Sets the current record's "language_id" value
 * @method ResourceLineTranslation setTargetText()  Sets the current record's "target_text" value
 * @method ResourceLineTranslation setRemarks()     Sets the current record's "remarks" value
 * @method ResourceLineTranslation setLine()        Sets the current record's "Line" value
 * @method ResourceLineTranslation setLanguage()    Sets the current record's "Language" value
 * 
 * @package    xliffeditor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseResourceLineTranslation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('resource_line_translation');
        $this->hasColumn('line_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('language_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('target_text', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('remarks', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ResourceLine as Line', array(
             'local' => 'line_id',
             'foreign' => 'id'));

        $this->hasOne('ProjectLanguage as Language', array(
             'local' => 'language_id',
             'foreign' => 'id'));
    }
}