<?php

/**
 * ProjectLanguage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    xliffeditor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProjectLanguage extends BaseProjectLanguage
{
	public function hasIcon() {
          return true;
        }

        public function getIconUrl() {
          switch($this->lang) {
            case 'en':
              $lang = 'gb';
              break;
            default:
              $lang = $this->lang;
              break;
          }
    
          return '/images/flags/'.$lang.'.png';
        }
}
