<?php

/**
 * ProjectLanguage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    xliffeditor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProjectLanguage extends BaseProjectLanguage
{
	public function hasIcon() {
          return true;
        }

        public function getIconUrl() {
          switch($this->lang) {
            case 'en':
              $lang = 'gb';
              break;
            default:
              $lang = $this->lang;
              break;
          }
    
          return '/images/flags/'.$lang.'.png';
        }

	public function getTotalTranslatedLineCount() {
 		$q = ResourceLineTranslationTable::getInstance()->createQuery('rlt')
			->select('COUNT(rlt.line_id)')
			->addWhere('rlt.language_id = ?', $this->id)
			->andWhere('rlt.line_id IN (SELECT rl.id FROM ResourceLine rl WHERE rl.resource_id IN (SELECT r.id FROM Resource r WHERE r.project_id = ?))', $this->project_id)
			;
		return $q->fetchOne(null, Doctrine_Core::HYDRATE_SINGLE_SCALAR);
        }

	public function getPercentageComplete() {
		$linesToTranslate = $this->Project->getTotalLineCount();
		if ($linesToTranslate == 0) return 0;

                $linesTranslated = $this->getTotalTranslatedLineCount();
               
               return (100 / $linesToTranslate) * $linesTranslated;
        }
}
