<?php

/**
 * ProjectLanguageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectLanguageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectLanguageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectLanguage');
    }
}