<?php

/**
 * Project
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    xliffeditor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Project extends BaseProject
{
    public function getFileCount()
    {
        $q = ResourceTable::getInstance()->createQuery('r')->select('COUNT(r.id)')->where('r.project_id = ?', $this->id);
        return $q->fetchOne(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
    }

    public function getLanguageCount()
    {
        $q = ProjectLanguageTable::getInstance()->createQuery('l')->select('COUNT(l.id)')->where('l.project_id = ?', $this->id);
        return $q->fetchOne(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
    }

    public function getPercentageComplete()
    {
        
        return 0;
    }

    public function getLanguage($langCode)
    {
        foreach ($this->Languages as $language) {
            if ($language->lang == $langCode) {
                return $language;
            }
        }
        return false;
    }
}
