<?php

/**
 * ResourceLineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResourceLineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResourceLineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ResourceLine');
    }
}