<?php

/**
 * ResourceLine
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    xliffeditor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ResourceLine extends BaseResourceLine
{
    public function getTargetText($lang, $default = FALSE)
    {
        $translation = $this->getTranslationLine($lang);
        if ($translation !== FALSE) {

            return $translation->target_text;

        } else {

            return $default;

        }
    }

    public function setTranslation($lang, $targetText, $note = null) {

        $translation = $this->getTranslationLine($lang);
        if ($translation === FALSE) {
            $translation = new ResourceLineTranslation();
            $translation->language_id = $this->getLanguageId($lang);
            $translation->line_id = $this->id;
            die('languageId = '.$lang.'  => '.$translation->language_id);
        }

        $translation->target_text = $targetText;
        $translation->save();

    }

    protected function getLanguageId($lang) {
        if (is_numeric($lang)) {
            return $lang;
        } elseif (is_string($lang)) {
            $language = $this->Resource->Project->getLanguage($lang);
            return $language->id;
        } elseif ($lang instanceof ProjectLanguage) {
            return $lang->id;
        }
        throw new sfException('Unknown language');
    }

    protected function getTranslationLine($lang) {
        $languageId = $this->getLanguageId($lang);

        foreach ($this->Translations as $translation) {
            if ($translation->language_id == $languageId) {
                return $translation;
            }
        }

        return false;
    }
}
