<?php

/**
 * ResourceLineTranslationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResourceLineTranslationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResourceLineTranslationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ResourceLineTranslation');
    }
}