<?php

/**
 * ResourceLine
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    xliffeditor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ResourceLine extends BaseResourceLine
{
  public function getTargetText($lang, $default = FALSE) {
    if (is_string($lang)) {
      $language = $this->Resource->Project->getLanguage($lang);
      $languageId = $language->id;
    } elseif (is_numeric($lang)) {
      $languageId = $lang;
    } elseif ($lang instanceof ProjectLanguage) {
      $languageId = $lang->id;
    }

    foreach($this->Translations as $translation) {
      if ($translation->language_id == $languageId) {
        return $translation->target_text;
      }
    }
    return $default;
  }
}
