<?php

/**
 * ResourceLineTranslationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResourceLineTranslationsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResourceLineTranslationsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ResourceLineTranslations');
    }
}