<?php

/**
 * Resource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    xliffeditor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Resource extends BaseResource
{
	public function getProjectSlug() {
		return $this->Project->slug;
        }
        public function getTotalLineCount() {
                $q = ResourceLineTable::getInstance()->createQuery('l')
                          ->select('COUNT(l.id)')->where('l.resource_id = ?', $this->id);
		return $q->fetchOne(null, Doctrine_Core::HYDRATE_SINGLE_SCALAR);
        }
	public function getTranslatedLineCount() {
		$q = ResourceLineTranslationTable::getInstance()->createQuery('lr')
                           ->select('COUNT(lr.line_id)')->where('lr.line_id IN (SELECT l.id FROM ResourceLine l WHERE l.resource_id = ?)', $this->id);
		return $q->fetchOne(null, Doctrine_Core::HYDRATE_SINGLE_SCALAR);
 	}
 	public function getPercentageComplete() {
                $languageCount = $this->Project->getLanguageCount();
		$linesToTranslate = $this->getTotalLineCount() * $languageCount;

 		if ($linesToTranslate == 0) return 0;
		$linesTranslated = $this->getTranslatedLineCount();

		return (100 / $linesToTranslate) * $linesTranslated;
	}
}
