<?php

/**
 * TranslationFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TranslationFileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TranslationFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TranslationFile');
    }
}