<?php

/**
 * TranslationProjectLanguageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TranslationProjectLanguageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TranslationProjectLanguageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TranslationProjectLanguage');
    }
}