# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        XLiff Editor
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    
    - http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css
    - main.css

  javascripts:
    - http://code.jquery.com/jquery-1.5.2.min.js
    - http://twitter.github.com/bootstrap/1.4.0/bootstrap-alerts.js
    - http://twitter.github.com/bootstrap/1.4.0/bootstrap-modal.js
    - http://twitter.github.com/bootstrap/1.4.0/bootstrap-dropdown.js

  has_layout:     true
  layout:         layout
