TranslationProject:
  columns:
    id: { type: integer, primary: true, autoincrement: true }
    name: { type: string(50), notnull: true }
    token: { type: string(32), notnull: true }
  
TranslationProjectLanguage:
  columns:
    id: { type: integer, primary: true, autoincrement: true }
    project_id: { type: integer, notnull: true }
    name: { type: string(50), notnull: true }
    lang: { type: string(5), notnull: true }
  relations:
    Project:
      class: TranslationProject
      local: project_id
      foreign: id
      foreignAlias: Languages

TranslationFile:
  columns:
    id: { type: integer, primary: true, autoincrement: true }
    project_id: { type: integer, notnull: true }
    name: { type: string(50), notnull: true }
    filename: { type: string(50), notnull: true }
  relations:
    Project:
      class: TranslationProject
      local: project_id
      foreign: id
      foreignAlias: Files

